version: "3.8"

services:
  carpark-service:
    build:
      context: .
      args:
        JAR_FILE: ./target/car-park-0.0.1-SNAPSHOT.jar
    container_name: carpark-service
    ports:
      - 8088:8088
    networks:
    - carpark-network
  redis:
    container_name: redis-for-carpark
    image: redis:7.0.11-alpine
    ports:
      - '6379:6379'
    #command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - carpark-network
  postgres:
    image: postgres:15.3-alpine
    restart: 'unless-stopped'
    container_name: postgres-for-carpark
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carpark
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Rootadmin1
      POSTGRES_SCHEMA: carpark
    networks:
      - carpark-network
volumes:
  redis:
    driver: local
networks:
  carpark-network:
    driver: bridge