server:
  error:
    include-stacktrace: on_param
    include-message: on_param
  port: ${SERVER_PORT:8088}
  forward-headers-strategy: none

spring:
  application:
    name: domain-core-service
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_updates: true
        jdbc:
          batch_size: 20
  data:
    redis:
      host: ${REDIS_URL:redis}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB_INDEX:0}
      global_ttl_minutes: 30 # 5 Seconds
      timeout: 5000 # 5 Seconds
      connect-timeout: 5000
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/carpark?currentSchema=carpark&serverTimezone=UTC
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:Rootadmin1}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
    schemas:
      - ${POSTGRES_SCHEMA:carpark}
fix:
  flyway:

#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: never
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceId: AUTO
#          jobStore:
#            tablePrefix: ${POSTGRES_SCHEMA}.qrtz_
#            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            misfireThreshold: 60000
#            clusterCheckinInterval: 5000
#            isClustered: true